addons:
  apt:
    packages:
    - graphviz
after_script:
- for f in packages/builds/logs/*.log; do echo "Logfile $f:"; cat $f; done
before_cache:
- rm -f standalone/pedigree-x64/build/hdd.img
- rm -f standalone/pedigree-x64/build/pedigree.iso
- rm -f standalone/pedigree-arm/build/hdd.img
- rm -f standalone/pedigree-arm/build/pedigree.iso
before_install: if [ "x$PACKAGE" != "x" ]; then docker pull miselin/pedigree; fi
branches:
  only:
  - master
cache:
  apt: true
  ccache: true
  directories:
  - standalone-x64
  - standalone-arm
  pip: true
install: pip install -r requirements.txt
language: python
matrix:
  allow_failures:
  - &id003
    env:
    - TARGET=amd64
    - PACKAGE=inetutils
    - CC=clang
    - CXX=clang++
    - &id001
      secure: ZiZk/cKj4PXaxpOt0AxJ2raY5tB43NBDGPO92pTsXO01rJvn/1T7sUkrT3DUWjsCH7itfqdGJCau5IGZdD8Vdsji0PcH4va1koaYW/4lLBT5cq2GxaQdkminSP2aEXBSrLV9/PdsP7wdcgL7PqW0/OeDaM0tF+gxOcWNmBz3dKg=
    os: linux
    python: '2.7'
    services: &id002
    - docker
    sudo: true
  - &id004
    env:
    - TARGET=arm
    - PACKAGE=inetutils
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id005
    env:
    - TARGET=amd64
    - PACKAGE=sqlite
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id006
    env:
    - TARGET=arm
    - PACKAGE=sqlite
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id007
    env:
    - TARGET=amd64
    - PACKAGE=pth
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id008
    env:
    - TARGET=arm
    - PACKAGE=pth
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id009
    env:
    - TARGET=amd64
    - PACKAGE=vttest
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id010
    env:
    - TARGET=arm
    - PACKAGE=vttest
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id011
    env:
    - TARGET=amd64
    - PACKAGE=pedigree-base
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id012
    env:
    - TARGET=arm
    - PACKAGE=pedigree-base
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id013
    env:
    - TARGET=amd64
    - PACKAGE=vim
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id014
    env:
    - TARGET=arm
    - PACKAGE=vim
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id015
    env:
    - TARGET=amd64
    - PACKAGE=sed
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id016
    env:
    - TARGET=arm
    - PACKAGE=sed
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id017
    env:
    - TARGET=amd64
    - PACKAGE=mtools
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id018
    env:
    - TARGET=arm
    - PACKAGE=mtools
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id019
    env:
    - TARGET=amd64
    - PACKAGE=netsurf
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id020
    env:
    - TARGET=arm
    - PACKAGE=netsurf
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id021
    env:
    - TARGET=amd64
    - PACKAGE=perl
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id022
    env:
    - TARGET=arm
    - PACKAGE=perl
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id023
    env:
    - TARGET=amd64
    - PACKAGE=mesa
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id024
    env:
    - TARGET=arm
    - PACKAGE=mesa
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id025
    env:
    - TARGET=amd64
    - PACKAGE=bsdtar
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id026
    env:
    - TARGET=arm
    - PACKAGE=bsdtar
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id027
    env:
    - TARGET=amd64
    - PACKAGE=pedigree-devel
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id028
    env:
    - TARGET=arm
    - PACKAGE=pedigree-devel
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id029
    env:
    - TARGET=amd64
    - PACKAGE=git
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id030
    env:
    - TARGET=arm
    - PACKAGE=git
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id031
    env:
    - TARGET=amd64
    - PACKAGE=nano
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id032
    env:
    - TARGET=arm
    - PACKAGE=nano
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id033
    env:
    - TARGET=amd64
    - PACKAGE=lua
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id034
    env:
    - TARGET=arm
    - PACKAGE=lua
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id035
    env:
    - TARGET=amd64
    - PACKAGE=less
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id036
    env:
    - TARGET=arm
    - PACKAGE=less
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id037
    env:
    - TARGET=amd64
    - PACKAGE=coreutils
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id038
    env:
    - TARGET=arm
    - PACKAGE=coreutils
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id039
    env:
    - TARGET=amd64
    - PACKAGE=python26
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id040
    env:
    - TARGET=arm
    - PACKAGE=python26
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id041
    env:
    - TARGET=amd64
    - PACKAGE=gnumake
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id042
    env:
    - TARGET=arm
    - PACKAGE=gnumake
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id043
    env:
    - TARGET=amd64
    - PACKAGE=grep
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id044
    env:
    - TARGET=arm
    - PACKAGE=grep
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id045
    env:
    - TARGET=amd64
    - PACKAGE=python27
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id046
    env:
    - TARGET=arm
    - PACKAGE=python27
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id047
    env:
    - TARGET=amd64
    - PACKAGE=m4
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id048
    env:
    - TARGET=arm
    - PACKAGE=m4
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id049
    env:
    - TARGET=amd64
    - PACKAGE=gawk
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id050
    env:
    - TARGET=arm
    - PACKAGE=gawk
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id051
    env:
    - TARGET=amd64
    - PACKAGE=gcc
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id052
    env:
    - TARGET=arm
    - PACKAGE=gcc
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id053
    env:
    - TARGET=amd64
    - PACKAGE=dropbear
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id054
    env:
    - TARGET=arm
    - PACKAGE=dropbear
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id055
    env:
    - TARGET=amd64
    - PACKAGE=prboom
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id056
    env:
    - TARGET=arm
    - PACKAGE=prboom
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id057
    env:
    - TARGET=amd64
    - PACKAGE=wget
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id058
    env:
    - TARGET=arm
    - PACKAGE=wget
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id059
    env:
    - TARGET=amd64
    - PACKAGE=bash
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id060
    env:
    - TARGET=arm
    - PACKAGE=bash
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id061
    env:
    - TARGET=amd64
    - PACKAGE=dosbox
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id062
    env:
    - TARGET=arm
    - PACKAGE=dosbox
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id063
    env:
    - TARGET=amd64
    - PACKAGE=grub2
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id064
    env:
    - TARGET=arm
    - PACKAGE=grub2
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id065
    env:
    - TARGET=amd64
    - PACKAGE=atk
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id066
    env:
    - TARGET=arm
    - PACKAGE=atk
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id067
    env:
    - TARGET=amd64
    - PACKAGE=pango
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id068
    env:
    - TARGET=arm
    - PACKAGE=pango
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id069
    env:
    - TARGET=amd64
    - PACKAGE=bind
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id070
    env:
    - TARGET=arm
    - PACKAGE=bind
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id071
    env:
    - TARGET=amd64
    - PACKAGE=e2fsprogs
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id072
    env:
    - TARGET=arm
    - PACKAGE=e2fsprogs
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id073
    env:
    - TARGET=amd64
    - PACKAGE=lynx
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id074
    env:
    - TARGET=arm
    - PACKAGE=lynx
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id075
    env:
    - TARGET=amd64
    - PACKAGE=diffutils
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id076
    env:
    - TARGET=arm
    - PACKAGE=diffutils
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id077
    env:
    - TARGET=amd64
    - PACKAGE=apache2
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id078
    env:
    - TARGET=arm
    - PACKAGE=apache2
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id079
    env:
    - TARGET=amd64
    - PACKAGE=binutils
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id080
    env:
    - TARGET=arm
    - PACKAGE=binutils
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id081
    env:
    - TARGET=amd64
    - PACKAGE=nasm
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id082
    env:
    - TARGET=arm
    - PACKAGE=nasm
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  include:
  - *id003
  - *id004
  - *id005
  - *id006
  - *id007
  - *id008
  - *id009
  - *id010
  - *id011
  - *id012
  - *id013
  - *id014
  - *id015
  - *id016
  - *id017
  - *id018
  - *id019
  - *id020
  - *id021
  - *id022
  - *id023
  - *id024
  - *id025
  - *id026
  - *id027
  - *id028
  - *id029
  - *id030
  - *id031
  - *id032
  - *id033
  - *id034
  - *id035
  - *id036
  - *id037
  - *id038
  - *id039
  - *id040
  - *id041
  - *id042
  - *id043
  - *id044
  - *id045
  - *id046
  - *id047
  - *id048
  - *id049
  - *id050
  - *id051
  - *id052
  - *id053
  - *id054
  - *id055
  - *id056
  - *id057
  - *id058
  - *id059
  - *id060
  - *id061
  - *id062
  - *id063
  - *id064
  - *id065
  - *id066
  - *id067
  - *id068
  - *id069
  - *id070
  - *id071
  - *id072
  - *id073
  - *id074
  - *id075
  - *id076
  - *id077
  - *id078
  - *id079
  - *id080
  - *id081
  - *id082
  - env:
    - DEPS_ONLY=y
    - TARGET=amd64
    - *id001
    os: linux
    python: '2.7'
  - env:
    - DEPS_ONLY=y
    - TARGET=arm
    - *id001
    os: linux
    python: '2.7'
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#pedigree-commits
    on_failure: always
    on_success: change
    template:
    - '%{repository}/%{branch} (%{commit} - %{author}): %{message}'
    - 'Build details: %{build_url}'
  slack:
    secure: T9GJHictl8hUOgGh5RRVmRMExqlWJByssoSYdgnFuHA8ugLXyvHyYaVjLPVcFE9yv7w+sQgki0ZIzCyUH/Hg6/UPwRaH8W4Cm57vQwhE+TUvfy6eRRvYT118X/9X3xkYwhNUks+uydP6oI9YTnvr1XrzB6L4htA7Ma/YKBDhLhg=
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
script: ./travis.sh
sudo: false
