addons:
  apt:
    packages:
    - fakechroot
after_script:
- for f in packages/builds/logs/*.log; do echo "Logfile $f:"; cat $f; done
cache:
  directories:
  - standalone
install: pip install -r requirements.txt
language: python
matrix:
  include:
  - env:
    - TARGET=amd64
    - PACKAGE=libtool
    - CC=clang
    - CXX=clang++
    - &id001
      secure: W9NNuKNiJf+vx1QR3K4Cyt3yBgRKRO2Raqt8szG5uryyRX777uqD7+mxekWJEsTdR7gQHStKXEZwA9tNnCQusN09gd8VG7j1RxxlyrjM3HNt0qwyFbZNrbIMKxBV2K2Y6lSljLm3DQd7yO9799rnlo9q6jygg/zhyMbfLlIshgA=
    os: linux
    python: '2.7'
    sudo: true
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#pedigree
    on_failure: always
    on_success: change
    template:
    - '%{repository}/%{branch} (%{commit} - %{author}): %{message}'
    - 'Build details: %{build_url}'
  slack:
    secure: T9GJHictl8hUOgGh5RRVmRMExqlWJByssoSYdgnFuHA8ugLXyvHyYaVjLPVcFE9yv7w+sQgki0ZIzCyUH/Hg6/UPwRaH8W4Cm57vQwhE+TUvfy6eRRvYT118X/9X3xkYwhNUks+uydP6oI9YTnvr1XrzB6L4htA7Ma/YKBDhLhg=
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
script: ./travis.sh
sudo: false
