addons:
  apt:
    packages:
    - graphviz
after_script:
- for f in packages/builds/logs/*.log; do echo "Logfile $f:"; cat $f; done
before_cache:
- rm -f standalone/pedigree-x64/build/hdd.img
- rm -f standalone/pedigree-x64/build/pedigree.iso
- rm -f standalone/pedigree-arm/build/hdd.img
- rm -f standalone/pedigree-arm/build/pedigree.iso
before_install: if [ "x$PACKAGE" != "x" ]; then docker pull miselin/pedigree; fi
branches:
  only:
  - master
cache:
  apt: true
  ccache: true
  directories:
  - standalone-x64
  - standalone-arm
  pip: true
install: pip install -r requirements.txt
language: python
matrix:
  allow_failures:
  - &id003
    env:
    - TARGET=amd64
    - PACKAGE=libtool
    - CC=clang
    - CXX=clang++
    - &id001
      secure: ZiZk/cKj4PXaxpOt0AxJ2raY5tB43NBDGPO92pTsXO01rJvn/1T7sUkrT3DUWjsCH7itfqdGJCau5IGZdD8Vdsji0PcH4va1koaYW/4lLBT5cq2GxaQdkminSP2aEXBSrLV9/PdsP7wdcgL7PqW0/OeDaM0tF+gxOcWNmBz3dKg=
    os: linux
    python: '2.7'
    services: &id002
    - docker
    sudo: true
  - &id004
    env:
    - TARGET=arm
    - PACKAGE=libtool
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id005
    env:
    - TARGET=amd64
    - PACKAGE=libbind
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  - &id006
    env:
    - TARGET=arm
    - PACKAGE=libbind
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    services: *id002
    sudo: true
  include:
  - *id003
  - *id004
  - *id005
  - *id006
  - env:
    - DEPS_ONLY=y
    - TARGET=amd64
    - *id001
    os: linux
    python: '2.7'
  - env:
    - DEPS_ONLY=y
    - TARGET=arm
    - *id001
    os: linux
    python: '2.7'
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#pedigree-commits
    on_failure: always
    on_success: change
    template:
    - '%{repository}/%{branch} (%{commit} - %{author}): %{message}'
    - 'Build details: %{build_url}'
  slack:
    secure: T9GJHictl8hUOgGh5RRVmRMExqlWJByssoSYdgnFuHA8ugLXyvHyYaVjLPVcFE9yv7w+sQgki0ZIzCyUH/Hg6/UPwRaH8W4Cm57vQwhE+TUvfy6eRRvYT118X/9X3xkYwhNUks+uydP6oI9YTnvr1XrzB6L4htA7Ma/YKBDhLhg=
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
script: travis_wait 50 ./travis.sh
sudo: false
