addons:
  apt:
    packages:
    - fakechroot
after_script:
- for f in packages/builds/logs/*.log; do echo "Logfile $f:"; cat $f; done
cache:
  directories:
  - standalone
install: pip install -r requirements.txt
language: python
matrix:
  include:
  - env:
    - TARGET=amd64
    - PACKAGE=inetutils
    - CC=clang
    - CXX=clang++
    - &id001
      secure: W9NNuKNiJf+vx1QR3K4Cyt3yBgRKRO2Raqt8szG5uryyRX777uqD7+mxekWJEsTdR7gQHStKXEZwA9tNnCQusN09gd8VG7j1RxxlyrjM3HNt0qwyFbZNrbIMKxBV2K2Y6lSljLm3DQd7yO9799rnlo9q6jygg/zhyMbfLlIshgA=
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=sqlite
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=pth
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=vttest
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=pedigree-base
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=vim
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=sed
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=mtools
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=netsurf
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=perl
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=mesa
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=bsdtar
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=pedigree-devel
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=git
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=nano
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=lua
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=less
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=coreutils
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=python26
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=gnumake
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=grep
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=python27
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=m4
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=gawk
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=gcc
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=dropbear
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=prboom
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=wget
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=bash
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=dosbox
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=grub2
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=atk
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=pango
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=bind
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=e2fsprogs
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=lynx
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=diffutils
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=apache2
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=binutils
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
  - env:
    - TARGET=amd64
    - PACKAGE=nasm
    - CC=clang
    - CXX=clang++
    - *id001
    os: linux
    python: '2.7'
    sudo: true
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#pedigree
    on_failure: always
    on_success: change
    template:
    - '%{repository}/%{branch} (%{commit} - %{author}): %{message}'
    - 'Build details: %{build_url}'
  slack:
    secure: T9GJHictl8hUOgGh5RRVmRMExqlWJByssoSYdgnFuHA8ugLXyvHyYaVjLPVcFE9yv7w+sQgki0ZIzCyUH/Hg6/UPwRaH8W4Cm57vQwhE+TUvfy6eRRvYT118X/9X3xkYwhNUks+uydP6oI9YTnvr1XrzB6L4htA7Ma/YKBDhLhg=
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
script: ./travis.sh
sudo: false
