sudo: false
language: python
# python:
#   - "2.7"
#   - "3.2"
#   - "3.3"
#   - "3.4"
matrix:
  include:
  - os: linux
    sudo: true
    compiler: gcc
    python: "2.7"
    env: PACKAGE=libtool TARGET=amd64
install: "pip install -r requirements.txt"
script: ./travis.sh
notifications:
  email: false
  # irc:
  #   channels:
  #   - chat.freenode.net#pedigree
  #   template:
  #   - ! '%{repository}/%{branch} (%{commit} - %{author}): %{message}'
  #   - ! 'Build details: %{build_url}'
  #   on_success: change
  #   on_failure: always
  # slack:
  #   secure: T9GJHictl8hUOgGh5RRVmRMExqlWJByssoSYdgnFuHA8ugLXyvHyYaVjLPVcFE9yv7w+sQgki0ZIzCyUH/Hg6/UPwRaH8W4Cm57vQwhE+TUvfy6eRRvYT118X/9X3xkYwhNUks+uydP6oI9YTnvr1XrzB6L4htA7Ma/YKBDhLhg=
addons:
  apt:
    packages:
      - fakechroot
cache:
  directories:
  - standalone
