#!/usr/bin/env bash

set -euo pipefail

python3 -m unittest -v \
    buildPackages_test \
    environment_test \
    support.audit_test \
    support.build_test \
    support.buildsystem_test \
    support.catalog_test \
    support.deferred_infrastructure_test \
    support.deps_test \
    support.steps_test \
    support.toolchain_test \
    support.util_test \
    packages.bash.package_test \
    packages.apache2.package_test \
    packages.apr.package_test \
    packages.apr-util.package_test \
    packages.bind.package_test \
    packages.binutils.package_test \
    packages.bsdtar.package_test \
    packages.ca_certificates.package_test \
    packages.cmake.package_test \
    packages.coreutils.package_test \
    packages.curl.package_test \
    packages.dialog.package_test \
    packages.e2fsprogs.package_test \
    packages.gawk.package_test \
    packages.gcc.package_test \
    packages.gdbm.package_test \
    packages.gettext.package_test \
    packages.git.package_test \
    packages.grep.package_test \
    packages.glib.package_test \
    packages.gnumake.package_test \
    packages.gzip.package_test \
    packages.harfbuzz.package_test \
    packages.inetutils.package_test \
    packages.libffi.package_test \
    packages.libgmp.package_test \
    packages.libtool.package_test \
    packages.lynx.package_test \
    packages.m4.package_test \
    packages.man-db.package_test \
    packages.mandoc.package_test \
    packages.mesa.package_test \
    packages.ncurses.package_test \
    packages.openssh_client.package_test \
    packages.openssh_sftp_server.package_test \
    packages.openssl.package_test \
    packages.perl.package_test \
    packages.pth.package_test \
    packages.pup.package_test \
    packages.python3.package_test \
    packages.readline.package_test \
    packages.sdl2.package_test \
    packages.sed.package_test \
    packages.slang.package_test \
    packages.sqlite.package_test \
    packages.vim.package_test \
    pup.dist_test \
    pup.pedigree_updater.commands.create_test \
    pup.pedigree_updater.commands.install_test \
    pup.pedigree_updater.commands.register_test \
    pup.pedigree_updater.commands.sync_test \
    pup.pedigree_updater.lib.http_test \
    pup.pedigree_updater.lib.util_test \
    scripts.migrate_package_blobs_test \
    scripts.publish_packages_test \
    scripts.build_codex_test \
    scripts.codex_app_server_probe_test \
    scripts.codex_cli_probe_test \
    scripts.codex_code_mode_probe_test \
    scripts.codex_integration_probe_test \
    scripts.codex_package_test \
    scripts.qualify_language_ports_test \
    scripts.build_v8_test
python3 -m compileall -q \
    buildPackages.py \
    buildInChroot.py \
    environment.py \
    support \
    packages \
    scripts \
    pup/pedigree_updater \
    pup/http/pup_http
