set(CMAKE_SYSTEM_NAME Pedigree)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/Modules")

set(PEDIGREE_TOOLCHAIN_ROOT "/opt/pedigree" CACHE PATH
    "Pedigree cross-toolchain root")
set(PEDIGREE_PORTS_SYSROOT "" CACHE PATH
    "Staged FHS root containing port dependencies")

set(_PEDIGREE_TARGET x86_64-pedigree)
set(_PEDIGREE_BIN "${PEDIGREE_TOOLCHAIN_ROOT}/bin")
set(_PEDIGREE_SYSROOT "${PEDIGREE_TOOLCHAIN_ROOT}/${_PEDIGREE_TARGET}")

set(CMAKE_C_COMPILER "${_PEDIGREE_BIN}/${_PEDIGREE_TARGET}-gcc")
set(CMAKE_CXX_COMPILER "${_PEDIGREE_BIN}/${_PEDIGREE_TARGET}-g++")
if(EXISTS "/usr/bin/ccache")
    set(CMAKE_C_COMPILER_LAUNCHER "/usr/bin/ccache")
    set(CMAKE_CXX_COMPILER_LAUNCHER "/usr/bin/ccache")
endif()
set(CMAKE_AR "${_PEDIGREE_BIN}/${_PEDIGREE_TARGET}-ar")
set(CMAKE_NM "${_PEDIGREE_BIN}/${_PEDIGREE_TARGET}-nm")
set(CMAKE_OBJCOPY "${_PEDIGREE_BIN}/${_PEDIGREE_TARGET}-objcopy")
set(CMAKE_OBJDUMP "${_PEDIGREE_BIN}/${_PEDIGREE_TARGET}-objdump")
set(CMAKE_RANLIB "${_PEDIGREE_BIN}/${_PEDIGREE_TARGET}-ranlib")
set(CMAKE_READELF "${_PEDIGREE_BIN}/${_PEDIGREE_TARGET}-readelf")
set(CMAKE_STRIP "${_PEDIGREE_BIN}/${_PEDIGREE_TARGET}-strip")
set(CMAKE_SYSROOT "${_PEDIGREE_SYSROOT}")
set(_PEDIGREE_COMMON_FLAGS "-O2 -pipe -m64 -march=x86-64 -D__PEDIGREE__")
set(_PEDIGREE_LDFLAGS "")
if(PEDIGREE_PORTS_SYSROOT)
    string(APPEND _PEDIGREE_COMMON_FLAGS
        " -I${PEDIGREE_PORTS_SYSROOT}/usr/include")
    string(APPEND _PEDIGREE_LDFLAGS
        " -L${PEDIGREE_PORTS_SYSROOT}/usr/lib"
        " -Wl,-rpath-link,${PEDIGREE_PORTS_SYSROOT}/usr/lib")
endif()
set(_PEDIGREE_CFLAGS "${_PEDIGREE_COMMON_FLAGS} -std=gnu17")

set(CMAKE_C_FLAGS_INIT "${_PEDIGREE_CFLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${_PEDIGREE_COMMON_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_PEDIGREE_LDFLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_PEDIGREE_LDFLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_PEDIGREE_LDFLAGS}")

set(CMAKE_FIND_ROOT_PATH "${_PEDIGREE_SYSROOT}")
if(PEDIGREE_PORTS_SYSROOT)
    list(PREPEND CMAKE_FIND_ROOT_PATH
        "${PEDIGREE_PORTS_SYSROOT}/usr"
        "${PEDIGREE_PORTS_SYSROOT}")
endif()
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
