#!/usr/bin/env python
'''
    PIMP: Package Installation & Management for Pedigree

    Copyright (c) 2010 Matthew Iselin

    Permission to use, copy, modify, and distribute this software for any
    purpose with or without fee is hereby granted, provided that the above
    copyright notice and this permission notice appear in all copies.

    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

    pimp: central script for simplicity
'''

import os, sys
from optparse import OptionParser

args = sys.argv

if len(args) < 2:
    print "Usage: pimp <operation> <operation_args>"
    exit()

potential_ops = ["makepkg", "regpkg"]
if not args[1] in potential_ops:
    print "Operation '" + args[1] + "' not supported."
    print "Supported operations: " + ', '.join(potential_ops)
    exit()

script_path = os.path.dirname(args[0])

runscript = "pimp-" + args[1]
__import__(runscript)
mod = sys.modules[runscript]

mod.main(args[2:])

'''
optParser = OptionParser(usage="%prog <operation> <op_args>",
                         version="pimp-regpkg 0.1")
optParser.add_option("--repo", dest="repoBase", help="""
    Path to the directory containing the local package repository. This will be
    where the new package will be created in. The package database should be in
    this directory (but use pimp-regpkg to register this package in the
    database.""".replace("    ", "").strip())
optParser.add_option("--deps", dest="depsList", help="""
    Space-separated list of packages the package being registered depends on.
    These packages do not need to exist in the repository yet.""".replace("    ", "").strip())
optParser.add_option("--name", dest="packageName", help="""
    The name of the package being registered.""".replace("    ", "").strip())
optParser.add_option("--ver", dest="packageVersion", help="""
    The version of the package being registered.""".replace("    ", "").strip())
'''

